CREATE TABLE BANK
(
    BANK_ID   LONG PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    PHONE_NUMBER VARCHAR(15)
);
CREATE TABLE ACCOUNT
(  ID LONG PRIMARY KEY AUTO_INCREMENT,
   EMAIL VARCHAR(255),
   BANK_ID LONG,
   FOREIGN KEY (BANK_ID) REFERENCES BANK(BANK_ID)
);