CREATE TABLE BANK
(
    BANK_ID   LONG PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);
CREATE TABLE ACCOUNT
(  ID LONG PRIMARY KEY AUTO_INCREMENT,
   ACCOUNT_TYPE VARCHAR(255),
   AMOUNT DOUBLE PRECISION,
   BANK_ID LONG,
   FOREIGN KEY (BANK_ID) REFERENCES BANK(BANK_ID)
);